/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { AgentAssignmentsListRelationFilter } from "../../agentAssignments/base/AgentAssignmentsListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { EnumPropertiesStatus } from "./EnumPropertiesStatus";
import { EnumPropertiesTypeField } from "./EnumPropertiesTypeField";

@InputType()
class PropertiesWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  address?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AgentAssignmentsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AgentAssignmentsListRelationFilter)
  @IsOptional()
  @Field(() => AgentAssignmentsListRelationFilter, {
    nullable: true,
  })
  agentAssignmentsItems?: AgentAssignmentsListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  price?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  size?: IntNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumPropertiesStatus,
  })
  @IsEnum(EnumPropertiesStatus)
  @IsOptional()
  @Field(() => EnumPropertiesStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumPropertiesTypeField,
  })
  @IsEnum(EnumPropertiesTypeField)
  @IsOptional()
  @Field(() => EnumPropertiesTypeField, {
    nullable: true,
  })
  typeField?: "Option1";
}

export { PropertiesWhereInput as PropertiesWhereInput };
